# Generated by Django 5.2.10 on 2026-01-31 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tarifa', models.CharField(choices=[('1', '1 - Básica'), ('1A', '1A - Cálido extremo'), ('1B', '1B - Cálido'), ('1C', '1C - Cálido templado'), ('1D', '1D - Cálido húmedo'), ('1E', '1E - Cálido muy cálido'), ('1F', '1F - Cálido extremo prolongado'), ('DAC', 'DAC - Doméstica Alto Consumo'), ('DESCONOZCO', 'No sé mi tarifa')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('consumo_kwh', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('total_recibo_mxn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lectura_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('lectura_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplicador', models.PositiveIntegerField(default=1)),
                ('subsidio_mxn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evidencia_archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costo_estimado_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown_json', models.JSONField(default=dict)),
                ('recomendaciones_json', models.JSONField(default=list)),
                ('supuestos_json', models.JSONField(default=list)),
                ('confianza_global', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='energy.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas_en_casa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Personas en casa')),
                ('cuartos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Número de cuartos')),
                ('ac_count', models.IntegerField(choices=[(0, 'No tengo'), (1, '1 unidad'), (2, '2 o más')], default=0, verbose_name='Unidades de A/C')),
                ('ac_horas_dia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Horas de uso A/C por día')),
                ('refrigeradores', models.IntegerField(choices=[(1, '1 refrigerador'), (2, '2 o más')], default=1, verbose_name='Refrigeradores')),
                ('ref_antiguedad', models.CharField(choices=[('new', 'Nuevo (menos de 5 años)'), ('mid', 'Medio (5-12 años)'), ('old', 'Antiguo (más de 12 años)')], default='mid', max_length=10, verbose_name='Antigüedad del refrigerador principal')),
                ('agua_caliente', models.CharField(choices=[('gas', 'Gas (boiler/calentador)'), ('elec', 'Eléctrico'), ('none', 'No uso agua caliente')], default='gas', max_length=10, verbose_name='Tipo de calentador de agua')),
                ('lavadora', models.BooleanField(default=True, verbose_name='¿Tiene lavadora?')),
                ('secadora', models.BooleanField(default=False, verbose_name='¿Tiene secadora eléctrica?')),
                ('home_office', models.BooleanField(default=False, verbose_name='¿Trabaja desde casa (home office)?')),
                ('bombeo_agua', models.BooleanField(default=False, verbose_name='¿Tiene bomba de agua (tinaco/cisterna)?')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='energy.bill')),
            ],
        ),
    ]
