# Generated by Django 5.2.10 on 2026-02-01 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_bill_periodo_basico_kwh_bill_periodo_excedente_kwh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='ac_count',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ac_horas_dia',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='agua_caliente',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='bombeo_agua',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='cuartos',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='home_office',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='lavadora',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='personas_en_casa',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ref_antiguedad',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='refrigeradores',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='secadora',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
    ]
