# Generated by Django 5.2.10 on 2026-02-01 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_remove_survey_ac_count_remove_survey_ac_horas_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consumo_kwh',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
